services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
       - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mariadbcontainer;port=3306;database=obstacledb;user=root;password=test123;
    networks:
      - appnet
networks:
    appnet: #Legge til appnet nettverket som er ekstern nettverk
       external: true
       name: appnet